"""cabinet tables

Revision ID: 4e5a0de7b980
Revises: b1c2d3e4f5a6
Create Date: 2026-09-05 09:46:30.875859
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4e5a0de7b980'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cab_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('lf_crm_id', sa.Integer(), nullable=True),
    sa.Column('lf_status', sa.String(length=20), nullable=True),
    sa.Column('lf_answer_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lf_balance_rub', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance_contacts', sa.Integer(), nullable=True),
    sa.Column('balance_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lf_error', sa.Text(), nullable=True),
    sa.Column('contact_cost', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('handling_cost', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('suppliers_default', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limit_default', sa.Integer(), server_default='5', nullable=False),
    sa.Column('weekdays', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schedule_applied_day', sa.Date(), nullable=True),
    sa.Column('hook_token', sa.String(length=64), nullable=False),
    sa.Column('tg_chat_id', sa.String(length=32), nullable=True),
    sa.Column('tg_connect_code', sa.String(length=32), nullable=True),
    sa.Column('contacts_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hook_token'),
    sa.UniqueConstraint('login')
    )
    op.create_index(op.f('ix_cab_clients_lf_crm_id'), 'cab_clients', ['lf_crm_id'], unique=False)
    op.create_table('cab_sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_cab_sessions_subject_id'), 'cab_sessions', ['subject_id'], unique=False)
    op.create_table('cab_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('requisites', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['cab_clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_index(op.f('ix_cab_agents_client_id'), 'cab_agents', ['client_id'], unique=False)
    op.create_table('cab_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['cab_clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'phone', name='uq_cab_blacklist')
    )
    op.create_table('cab_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['cab_clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'name', name='uq_cab_company')
    )
    op.create_index(op.f('ix_cab_companies_client_id'), 'cab_companies', ['client_id'], unique=False)
    op.create_table('cab_inbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('state', sa.String(length=8), server_default='pending', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['cab_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cab_inbox_state', 'cab_inbox', ['state'], unique=False)
    op.create_table('cab_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='new', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['cab_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_integrations_client_id'), 'cab_integrations', ['client_id'], unique=False)
    op.create_table('cab_resource_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['cab_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_resource_lists_client_id'), 'cab_resource_lists', ['client_id'], unique=False)
    op.create_table('cab_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('requisites', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['cab_agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_payouts_agent_id'), 'cab_payouts', ['agent_id'], unique=False)
    op.create_table('cab_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['cab_companies.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['cab_resource_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_resources_list_id'), 'cab_resources', ['list_id'], unique=False)
    op.create_table('cab_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('lf_source_id', sa.Integer(), nullable=True),
    sa.Column('lf_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lf_will_work', sa.Boolean(), nullable=True),
    sa.Column('lf_dirty', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('lf_error', sa.Text(), nullable=True),
    sa.Column('suppliers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limit', sa.Integer(), server_default='5', nullable=False),
    sa.Column('geo_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled_by_user', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enabled_by_schedule', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('contacts_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('contacts_today', sa.Integer(), server_default='0', nullable=False),
    sa.Column('repeats_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lf_sebes_14', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lf_success_14', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('found_by_agent_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['cab_clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['cab_companies.id'], ),
    sa.ForeignKeyConstraint(['found_by_agent_id'], ['cab_agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'phone', name='uq_cab_source_phone')
    )
    op.create_index('ix_cab_sources_client', 'cab_sources', ['client_id', 'enabled_by_user'], unique=False)
    op.create_index(op.f('ix_cab_sources_lf_source_id'), 'cab_sources', ['lf_source_id'], unique=False)
    op.create_table('cab_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('price_per_source', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('limit_sources', sa.Integer(), server_default='0', nullable=False),
    sa.Column('to_purchase', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('purchase_limit', sa.Integer(), server_default='5', nullable=False),
    sa.Column('purchase_suppliers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['cab_clients.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['cab_resource_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_tasks_client_id'), 'cab_tasks', ['client_id'], unique=False)
    op.create_table('cab_contacts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('lf_answer_id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('operator', sa.String(length=60), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('source_tag', sa.String(length=80), nullable=True),
    sa.Column('supplier', sa.String(length=8), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('lf_status', sa.String(length=20), nullable=True),
    sa.Column('bought_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pulled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hook_status', sa.String(length=16), nullable=True),
    sa.Column('hook_status_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['cab_clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['cab_companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['cab_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lf_answer_id')
    )
    op.create_index('ix_cab_contacts_client_bought', 'cab_contacts', ['client_id', 'bought_at'], unique=False)
    op.create_index('ix_cab_contacts_client_phone', 'cab_contacts', ['client_id', 'phone'], unique=False)
    op.create_index(op.f('ix_cab_contacts_company_id'), 'cab_contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_cab_contacts_source_id'), 'cab_contacts', ['source_id'], unique=False)
    op.create_table('cab_found_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['cab_agents.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['cab_clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['cab_companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['cab_sources.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['cab_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'phone', name='uq_cab_found_phone')
    )
    op.create_index(op.f('ix_cab_found_sources_agent_id'), 'cab_found_sources', ['agent_id'], unique=False)
    op.create_index(op.f('ix_cab_found_sources_client_id'), 'cab_found_sources', ['client_id'], unique=False)
    op.create_index(op.f('ix_cab_found_sources_task_id'), 'cab_found_sources', ['task_id'], unique=False)
    op.create_table('cab_task_agents',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['cab_agents.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['cab_tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'agent_id')
    )
    op.create_table('cab_outbox',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=8), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_try_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['cab_clients.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['cab_contacts.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['cab_integrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'contact_id', name='uq_cab_outbox_once')
    )
    op.create_index('ix_cab_outbox_state', 'cab_outbox', ['state', 'next_try_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cab_outbox_state', table_name='cab_outbox')
    op.drop_table('cab_outbox')
    op.drop_table('cab_task_agents')
    op.drop_index(op.f('ix_cab_found_sources_task_id'), table_name='cab_found_sources')
    op.drop_index(op.f('ix_cab_found_sources_client_id'), table_name='cab_found_sources')
    op.drop_index(op.f('ix_cab_found_sources_agent_id'), table_name='cab_found_sources')
    op.drop_table('cab_found_sources')
    op.drop_index(op.f('ix_cab_contacts_source_id'), table_name='cab_contacts')
    op.drop_index(op.f('ix_cab_contacts_company_id'), table_name='cab_contacts')
    op.drop_index('ix_cab_contacts_client_phone', table_name='cab_contacts')
    op.drop_index('ix_cab_contacts_client_bought', table_name='cab_contacts')
    op.drop_table('cab_contacts')
    op.drop_index(op.f('ix_cab_tasks_client_id'), table_name='cab_tasks')
    op.drop_table('cab_tasks')
    op.drop_index(op.f('ix_cab_sources_lf_source_id'), table_name='cab_sources')
    op.drop_index('ix_cab_sources_client', table_name='cab_sources')
    op.drop_table('cab_sources')
    op.drop_index(op.f('ix_cab_resources_list_id'), table_name='cab_resources')
    op.drop_table('cab_resources')
    op.drop_index(op.f('ix_cab_payouts_agent_id'), table_name='cab_payouts')
    op.drop_table('cab_payouts')
    op.drop_index(op.f('ix_cab_resource_lists_client_id'), table_name='cab_resource_lists')
    op.drop_table('cab_resource_lists')
    op.drop_index(op.f('ix_cab_integrations_client_id'), table_name='cab_integrations')
    op.drop_table('cab_integrations')
    op.drop_index('ix_cab_inbox_state', table_name='cab_inbox')
    op.drop_table('cab_inbox')
    op.drop_index(op.f('ix_cab_companies_client_id'), table_name='cab_companies')
    op.drop_table('cab_companies')
    op.drop_table('cab_blacklist')
    op.drop_index(op.f('ix_cab_agents_client_id'), table_name='cab_agents')
    op.drop_table('cab_agents')
    op.drop_index(op.f('ix_cab_sessions_subject_id'), table_name='cab_sessions')
    op.drop_table('cab_sessions')
    op.drop_index(op.f('ix_cab_clients_lf_crm_id'), table_name='cab_clients')
    op.drop_table('cab_clients')
    # ### end Alembic commands ###
