"""initial

Revision ID: 4a895d484258
Revises: 
Create Date: 2026-09-03 11:59:18.442113
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4a895d484258'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lg_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('cost_per_contact', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('cost_per_handling', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('comment_fresh_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('post_freeze_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('donor_pause_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('resend_after_days', sa.Integer(), server_default='60', nullable=False),
    sa.Column('probe_mode', sa.String(length=10), server_default='manual', nullable=False),
    sa.Column('probe_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('probe_hook_token', sa.String(length=120), nullable=True),
    sa.Column('crm_webhook_url', sa.String(length=500), nullable=True),
    sa.Column('crm_secret', sa.String(length=120), nullable=True),
    sa.Column('send_mode', sa.String(length=10), server_default='auto', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lg_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(length=6), server_default='info', nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=20), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notified', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_at', 'lg_events', ['at'], unique=False)
    op.create_index('ix_events_entity', 'lg_events', ['entity', 'entity_id'], unique=False)
    op.create_table('lg_inbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('raw_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('remote_ip', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=8), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_inbox_state', 'lg_inbox', ['state'], unique=False)
    op.create_table('lg_search_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('stage', sa.String(length=14), server_default='collecting', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('collected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('passed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rejected_inactive', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rejected_activity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confident', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unclear', sa.Integer(), server_default='0', nullable=False),
    sa.Column('distributed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stage_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lg_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('ig_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('ig_id', sa.String(length=40), nullable=True),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('last_post_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('is_business', sa.Boolean(), nullable=True),
    sa.Column('roles', sa.String(length=12), server_default='commenter', nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('city_source', sa.String(length=10), nullable=True),
    sa.Column('activity_kind', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('phone_source', sa.String(length=10), nullable=True),
    sa.Column('probe_status', sa.String(length=16), nullable=True),
    sa.Column('probed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('probe_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['lg_cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_ig_accounts_city_id'), 'ig_accounts', ['city_id'], unique=False)
    op.create_index(op.f('ix_ig_accounts_ig_id'), 'ig_accounts', ['ig_id'], unique=False)
    op.create_index(op.f('ix_ig_accounts_phone'), 'ig_accounts', ['phone'], unique=False)
    op.create_table('lg_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('ig_id', sa.String(length=40), nullable=True),
    sa.Column('found_by', sa.String(length=200), nullable=True),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('last_post_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activity_kind', sa.String(length=30), nullable=True),
    sa.Column('activity_ok', sa.Boolean(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('city_name_raw', sa.String(length=80), nullable=True),
    sa.Column('city_confidence', sa.Float(), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=12), server_default='collected', nullable=False),
    sa.Column('reject_reason', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['lg_cities.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['lg_search_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'username', name='uq_candidate_task_username')
    )
    op.create_index('ix_candidates_task_state', 'lg_candidates', ['task_id', 'state'], unique=False)
    op.create_table('lg_rejects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('search_task_id', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_task_id'], ['lg_search_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('lg_stats_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hook', sa.String(length=80), server_default='', nullable=False),
    sa.Column('category', sa.String(length=40), server_default='', nullable=False),
    sa.Column('new_posts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('growth_posts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('commenters', sa.Integer(), server_default='0', nullable=False),
    sa.Column('leads', sa.Integer(), server_default='0', nullable=False),
    sa.Column('probed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('with_phone', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('applications', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('spend_contact', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('spend_handling', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['lg_cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'city_id', 'donor_id', 'hook', 'category', name='uq_stats_slice')
    )
    op.create_index('ix_stats_city_day', 'lg_stats_daily', ['city_id', 'day'], unique=False)
    op.create_table('lg_donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=14), server_default='new', nullable=False),
    sa.Column('intake_stage', sa.String(length=10), nullable=True),
    sa.Column('found_via', sa.String(length=16), server_default='manual', nullable=False),
    sa.Column('search_task_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_reason', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['ig_accounts.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['lg_cities.id'], ),
    sa.ForeignKeyConstraint(['search_task_id'], ['lg_search_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'city_id', name='uq_donor_account_city')
    )
    op.create_index('ix_donors_city_status', 'lg_donors', ['city_id', 'status'], unique=False)
    op.create_index(op.f('ix_lg_donors_account_id'), 'lg_donors', ['account_id'], unique=False)
    op.create_table('lg_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=10), nullable=False),
    sa.Column('external_id', sa.String(length=60), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('purpose', sa.String(length=300), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('search_task_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lines', sa.Integer(), server_default='0', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='50', nullable=False),
    sa.Column('state', sa.String(length=10), server_default='queued', nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_imported', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['lg_cities.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['lg_donors.id'], ),
    sa.ForeignKeyConstraint(['search_task_id'], ['lg_search_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_external', 'lg_jobs', ['provider', 'external_id'], unique=False)
    op.create_index('ix_jobs_provider_state', 'lg_jobs', ['provider', 'state'], unique=False)
    op.create_table('lg_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortcode', sa.String(length=40), nullable=False),
    sa.Column('ig_post_id', sa.String(length=60), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('city_source', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('product_type', sa.String(length=20), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comments_count_prev', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comments_delta', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_growth_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zero_growth_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_selling', sa.Boolean(), nullable=True),
    sa.Column('offer', sa.String(length=300), nullable=True),
    sa.Column('hook', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('cta_type', sa.String(length=60), nullable=True),
    sa.Column('code_word', sa.String(length=60), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monitor_status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('collected_comments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ig_accounts.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['lg_cities.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['lg_donors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortcode')
    )
    op.create_index('ix_posts_city_published', 'lg_posts', ['city_id', 'published_at'], unique=False)
    op.create_index('ix_posts_donor_published', 'lg_posts', ['donor_id', 'published_at'], unique=False)
    op.create_index('ix_posts_monitor', 'lg_posts', ['monitor_status', 'is_selling'], unique=False)
    op.create_table('lg_comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ig_comment_id', sa.String(length=40), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('author_account_id', sa.Integer(), nullable=True),
    sa.Column('author_username', sa.String(length=150), nullable=False),
    sa.Column('author_ig_id', sa.String(length=40), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('written_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=10), server_default='parserim', nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('is_donor_reply', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('qualification', sa.String(length=12), server_default='pending', nullable=False),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.String(length=300), nullable=True),
    sa.Column('ai_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manual_override', sa.String(length=8), nullable=True),
    sa.Column('age_distance_days', sa.Integer(), nullable=True),
    sa.Column('text_purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_account_id'], ['ig_accounts.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['lg_cities.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['lg_jobs.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['lg_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ig_comment_id')
    )
    op.create_index('ix_comments_author', 'lg_comments', ['author_username'], unique=False)
    op.create_index('ix_comments_city_written', 'lg_comments', ['city_id', 'written_at'], unique=False)
    op.create_index('ix_comments_post', 'lg_comments', ['post_id'], unique=False)
    op.create_index('ix_comments_qualification', 'lg_comments', ['qualification'], unique=False)
    op.create_table('lg_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('phone_from', sa.String(length=10), nullable=True),
    sa.Column('probe_status', sa.String(length=12), server_default='pending', nullable=False),
    sa.Column('probed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('probe_ref', sa.String(length=80), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outbound_status', sa.String(length=10), server_default='pending', nullable=False),
    sa.Column('crm_status', sa.String(length=14), server_default='new', nullable=False),
    sa.Column('crm_comment', sa.Text(), nullable=True),
    sa.Column('crm_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_contact', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('cost_handling', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ig_accounts.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['lg_cities.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['lg_comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['lg_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id')
    )
    op.create_index('ix_leads_account', 'lg_leads', ['account_id'], unique=False)
    op.create_index('ix_leads_city_created', 'lg_leads', ['city_id', 'created_at'], unique=False)
    op.create_index('ix_leads_probe', 'lg_leads', ['city_id', 'probe_status'], unique=False)
    op.create_table('lg_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=8), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_try_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lg_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_state_next', 'lg_outbox', ['state', 'next_try_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_state_next', table_name='lg_outbox')
    op.drop_table('lg_outbox')
    op.drop_index('ix_leads_probe', table_name='lg_leads')
    op.drop_index('ix_leads_city_created', table_name='lg_leads')
    op.drop_index('ix_leads_account', table_name='lg_leads')
    op.drop_table('lg_leads')
    op.drop_index('ix_comments_qualification', table_name='lg_comments')
    op.drop_index('ix_comments_post', table_name='lg_comments')
    op.drop_index('ix_comments_city_written', table_name='lg_comments')
    op.drop_index('ix_comments_author', table_name='lg_comments')
    op.drop_table('lg_comments')
    op.drop_index('ix_posts_monitor', table_name='lg_posts')
    op.drop_index('ix_posts_donor_published', table_name='lg_posts')
    op.drop_index('ix_posts_city_published', table_name='lg_posts')
    op.drop_table('lg_posts')
    op.drop_index('ix_jobs_provider_state', table_name='lg_jobs')
    op.drop_index('ix_jobs_external', table_name='lg_jobs')
    op.drop_table('lg_jobs')
    op.drop_index(op.f('ix_lg_donors_account_id'), table_name='lg_donors')
    op.drop_index('ix_donors_city_status', table_name='lg_donors')
    op.drop_table('lg_donors')
    op.drop_index('ix_stats_city_day', table_name='lg_stats_daily')
    op.drop_table('lg_stats_daily')
    op.drop_table('lg_rejects')
    op.drop_index('ix_candidates_task_state', table_name='lg_candidates')
    op.drop_table('lg_candidates')
    op.drop_index(op.f('ix_ig_accounts_phone'), table_name='ig_accounts')
    op.drop_index(op.f('ix_ig_accounts_ig_id'), table_name='ig_accounts')
    op.drop_index(op.f('ix_ig_accounts_city_id'), table_name='ig_accounts')
    op.drop_table('ig_accounts')
    op.drop_table('lg_settings')
    op.drop_table('lg_search_tasks')
    op.drop_index('ix_inbox_state', table_name='lg_inbox')
    op.drop_table('lg_inbox')
    op.drop_index('ix_events_entity', table_name='lg_events')
    op.drop_index('ix_events_at', table_name='lg_events')
    op.drop_table('lg_events')
    op.drop_table('lg_cities')
    # ### end Alembic commands ###
